/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view.Sistema.InternoSistema;

import java.awt.event.KeyEvent;
import manipuladores.ManipuladorAssunto;
import modelo.Assunto;
import view.TelaEntrar;

/**
 *
 * @author pedro
 */
public class AssuntosEditar extends javax.swing.JInternalFrame {

    /**
     * Creates new form AssuntosEditar
     */
    public AssuntosEditar() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txtID = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txtNovoNome = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtNovaQntd = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        FUNDO = new javax.swing.JLabel();

        setClosable(true);
        setTitle("Edição");
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel1.setText("ID do Assunto");

        txtID.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N

        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel2.setText("Novo nome");

        txtNovoNome.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N

        jLabel3.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel3.setText("Nova quantidade");

        txtNovaQntd.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        txtNovaQntd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNovaQntdActionPerformed(evt);
            }
        });
        txtNovaQntd.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtNovaQntdKeyPressed(evt);
            }
        });

        jButton1.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jButton1.setText("OK");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(txtNovaQntd, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton1))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(txtNovoNome, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3)
                            .addComponent(jLabel2)
                            .addComponent(txtID, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 150, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtID, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtNovoNome, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtNovaQntd, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(31, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addContainerGap())
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 350, 230));

        FUNDO.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        FUNDO.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/FUNDO2.png"))); // NOI18N
        getContentPane().add(FUNDO, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 399, 282));

        setBounds(0, 0, 400, 300);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        manipuladores.ManipuladorAssunto MpAss = new ManipuladorAssunto();
        Assunto assunto = new Assunto();
        int id_assunto;
        id_assunto = Integer.parseInt(txtID.getText());
        int novaQntd;
        novaQntd = Integer.parseInt(txtNovaQntd.getText());
        String dataEdicao = TelaEntrar.getDateTime();
        assunto.setId(id_assunto);
        assunto.setNome(txtNovoNome.getText());
        assunto.setQuantidade(novaQntd);
        assunto.setDataCadastro(dataEdicao);
        assunto.setCod_usuario(TelaEntrar.usuario().getCod());
        MpAss.Edicao(assunto);
        this.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void txtNovaQntdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNovaQntdActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNovaQntdActionPerformed

    private void txtNovaQntdKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNovaQntdKeyPressed
        if(evt.getKeyCode() == KeyEvent.VK_ENTER){
            manipuladores.ManipuladorAssunto MpAss = new ManipuladorAssunto();
            Assunto assunto = new Assunto();
            int id_assunto;
            id_assunto = Integer.parseInt(txtID.getText());
            int novaQntd;
            novaQntd = Integer.parseInt(txtNovaQntd.getText());
            String dataEdicao = TelaEntrar.getDateTime();
            assunto.setId(id_assunto);
            assunto.setNome(txtNovoNome.getText());
            assunto.setQuantidade(novaQntd);
            assunto.setDataCadastro(dataEdicao);
            assunto.setCod_usuario(TelaEntrar.usuario().getCod());
            MpAss.Edicao(assunto);
            this.dispose();
        } 
    }//GEN-LAST:event_txtNovaQntdKeyPressed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel FUNDO;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField txtID;
    private javax.swing.JTextField txtNovaQntd;
    private javax.swing.JTextField txtNovoNome;
    // End of variables declaration//GEN-END:variables
}
