/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view.Sistema;

import modelo.Usuario;
import view.TelaEntrar;
import view.TelaInicial;

/**
 *
 * @author pedro
 */
public class Sistema extends javax.swing.JFrame {

    private Usuario usuario;
    
    public Sistema() {
        initComponents();
        usuario = this.getUsuario();
    }

    public Usuario getUsuario() {
        return usuario;
    }

    public void setUsuario(Usuario usuario) {
        this.usuario = usuario;
    }
   
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButtonCadastroAssunto = new javax.swing.JButton();
        jButtonCadastroQuestao = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jButtonSair = new javax.swing.JButton();
        FUNDO = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setTitle("Cadastrar");
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButtonCadastroAssunto.setFont(new java.awt.Font("Times New Roman", 3, 18)); // NOI18N
        jButtonCadastroAssunto.setText("-- Assuntos --");
        jButtonCadastroAssunto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCadastroAssuntoActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonCadastroAssunto, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 70, 200, -1));
        jButtonCadastroAssunto.getAccessibleContext().setAccessibleDescription("");

        jButtonCadastroQuestao.setBackground(new java.awt.Color(255, 255, 255));
        jButtonCadastroQuestao.setFont(new java.awt.Font("Times New Roman", 3, 18)); // NOI18N
        jButtonCadastroQuestao.setText("-- Questões --");
        jButtonCadastroQuestao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCadastroQuestaoActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonCadastroQuestao, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 140, 200, -1));

        jLabel1.setFont(new java.awt.Font("Times New Roman", 3, 18)); // NOI18N
        jLabel1.setText("OU");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 110, 30, -1));

        jButtonSair.setFont(new java.awt.Font("Times New Roman", 3, 14)); // NOI18N
        jButtonSair.setText("Sair");
        jButtonSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSairActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonSair, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 220, 60, -1));

        FUNDO.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/FUNDO2.png"))); // NOI18N
        getContentPane().add(FUNDO, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        setSize(new java.awt.Dimension(516, 289));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonCadastroQuestaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCadastroQuestaoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonCadastroQuestaoActionPerformed

    private void jButtonSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSairActionPerformed
        TelaInicial tela = new TelaInicial();
        tela.setVisible(true);
        dispose();
    }//GEN-LAST:event_jButtonSairActionPerformed

    private void jButtonCadastroAssuntoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCadastroAssuntoActionPerformed
        SistemaAssuntos SysAssTela = new SistemaAssuntos();
        SysAssTela.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButtonCadastroAssuntoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Sistema.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Sistema.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Sistema.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Sistema.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Sistema().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel FUNDO;
    private javax.swing.JButton jButtonCadastroAssunto;
    private javax.swing.JButton jButtonCadastroQuestao;
    private javax.swing.JButton jButtonSair;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
