/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view.Sistema;

import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import manipuladores.ManipuladorQuestao;
import modelo.Questao;
import modelo.Usuario;
import view.Sistema.InternoSistema.ListagemQuestoes;
import view.Sistema.InternoSistema.QuestoesExcluir;
import view.Sistema.InternoSistema.QuestoesListagem;
import view.TelaEntrar;

/**
 *
 * @author pedro
 */
public class SistemaQuestoes extends javax.swing.JFrame {

    /**
     * Creates new form SistemaQuestoes
     */
    private Usuario usuario;
    
    public SistemaQuestoes() {
        initComponents();
        choiceTipos.add("Pergunta aberta");
        choiceTipos.add("Pergunta objetiva com única escolha");
        choiceTipos.add("Pergunta objetiva com múltipla resposta");
        choiceTipos.add("Verdadeira ou falsa");
        Usuario usuario = new Usuario();
    }

    public Usuario getUsuario() {
        return usuario;
    }

    public void setUsuario(Usuario usuario) {
        this.usuario = usuario;
    }
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        icon = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtID = new javax.swing.JTextField();
        choiceTipos = new java.awt.Choice();
        textAreaQuestao = new java.awt.TextArea();
        textAreaResposta = new java.awt.TextArea();
        txtAssunto = new javax.swing.JTextField();
        jButtonCadastrar = new javax.swing.JButton();
        FUNDO = new javax.swing.JLabel();
        INICIO = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenuQuestao = new javax.swing.JMenu();
        jMenuItemEditar = new javax.swing.JMenuItem();
        jMenuItemExcluir = new javax.swing.JMenuItem();
        jMenuItemListar = new javax.swing.JMenuItem();
        jMenuItemVoltar = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setTitle("Sistema/Questões");
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        icon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/IconQuestion.jpg"))); // NOI18N
        icon.setMaximumSize(new java.awt.Dimension(250, 290));
        icon.setMinimumSize(new java.awt.Dimension(250, 290));
        icon.setPreferredSize(new java.awt.Dimension(250, 290));
        jPanel1.add(icon, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 0, 130, 170));

        jLabel6.setFont(new java.awt.Font("Times New Roman", 3, 18)); // NOI18N
        jLabel6.setText("Cadastro de Questões");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 11, -1, -1));

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel1.setText("ID");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 51, -1, -1));

        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel2.setText("Pergunta");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 122, -1, -1));

        jLabel3.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel3.setText("Tipo");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 272, -1, -1));

        jLabel4.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel4.setText("Resposta");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 120, -1, -1));

        jLabel5.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel5.setText("Assunto da questão");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 317, -1, -1));

        txtID.setFont(new java.awt.Font("Times New Roman", 0, 11)); // NOI18N
        txtID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtIDActionPerformed(evt);
            }
        });
        jPanel1.add(txtID, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 74, 40, 30));

        choiceTipos.setFont(new java.awt.Font("Times New Roman", 0, 11)); // NOI18N
        choiceTipos.setName("Tipos"); // NOI18N
        choiceTipos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                choiceTiposMouseClicked(evt);
            }
        });
        jPanel1.add(choiceTipos, new org.netbeans.lib.awtextra.AbsoluteConstraints(46, 272, 214, -1));

        textAreaQuestao.setFont(new java.awt.Font("Times New Roman", 0, 11)); // NOI18N
        textAreaQuestao.setMaximumSize(new java.awt.Dimension(250, 60));
        textAreaQuestao.setMinimumSize(new java.awt.Dimension(250, 60));
        jPanel1.add(textAreaQuestao, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 149, 290, 100));

        textAreaResposta.setFont(new java.awt.Font("Times New Roman", 0, 11)); // NOI18N
        textAreaResposta.setMaximumSize(new java.awt.Dimension(200, 60));
        textAreaResposta.setMinimumSize(new java.awt.Dimension(200, 60));
        jPanel1.add(textAreaResposta, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 150, 180, 100));

        txtAssunto.setFont(new java.awt.Font("Times New Roman", 0, 11)); // NOI18N
        txtAssunto.setPreferredSize(new java.awt.Dimension(50, 30));
        jPanel1.add(txtAssunto, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 343, 175, -1));

        jButtonCadastrar.setFont(new java.awt.Font("Times New Roman", 3, 18)); // NOI18N
        jButtonCadastrar.setText("Cadastrar");
        jButtonCadastrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCadastrarActionPerformed(evt);
            }
        });
        jPanel1.add(jButtonCadastrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 340, -1, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 40, 630, 480));

        FUNDO.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/Question.jpg"))); // NOI18N
        getContentPane().add(FUNDO, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 640, 600));
        getContentPane().add(INICIO, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 640, 580));

        jMenuQuestao.setText("Questão");

        jMenuItemEditar.setText("Editar");
        jMenuQuestao.add(jMenuItemEditar);

        jMenuItemExcluir.setText("Excluir");
        jMenuItemExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemExcluirActionPerformed(evt);
            }
        });
        jMenuQuestao.add(jMenuItemExcluir);

        jMenuItemListar.setText("Listar");
        jMenuItemListar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemListarActionPerformed(evt);
            }
        });
        jMenuQuestao.add(jMenuItemListar);

        jMenuItemVoltar.setText("Voltar");
        jMenuItemVoltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemVoltarActionPerformed(evt);
            }
        });
        jMenuQuestao.add(jMenuItemVoltar);

        jMenuBar1.add(jMenuQuestao);

        setJMenuBar(jMenuBar1);

        setSize(new java.awt.Dimension(640, 600));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItemListarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemListarActionPerformed
        ListagemQuestoes QstListar = new ListagemQuestoes();
        QstListar.setVisible(true);
    }//GEN-LAST:event_jMenuItemListarActionPerformed

    private void jMenuItemExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemExcluirActionPerformed
        QuestoesExcluir ExclusaoQst = new QuestoesExcluir();
        icon.add(ExclusaoQst);
        ExclusaoQst.setVisible(true);
    }//GEN-LAST:event_jMenuItemExcluirActionPerformed

    private void txtIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtIDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtIDActionPerformed

    private void choiceTiposMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_choiceTiposMouseClicked
        //getContentPane().add(choiceTipos, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 0, 0));
    }//GEN-LAST:event_choiceTiposMouseClicked

    private void jButtonCadastrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCadastrarActionPerformed
        setUsuario(TelaEntrar.usuario());
        Questao questao = new Questao();
        ManipuladorQuestao MpQst = new ManipuladorQuestao();
        int ID;
        ID = Integer.parseInt(txtID.getText());
        questao.setId(ID);
        questao.setResposta(textAreaResposta.getText());
        questao.setTexto(textAreaQuestao.getText());
        questao.setTipo(choiceTipos.getSelectedItem());
        int ID_Assunto = MpQst.busca_ID_Assunto(getUsuario(), txtAssunto.getText());
        questao.setId_Assunto(ID_Assunto);
        questao.setCod_usuario(getUsuario().getCod());
        MpQst.cadastrar(questao);
    }//GEN-LAST:event_jButtonCadastrarActionPerformed

    private void jMenuItemVoltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemVoltarActionPerformed
        Sistema Sys = new Sistema();
        Sys.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jMenuItemVoltarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SistemaQuestoes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SistemaQuestoes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SistemaQuestoes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SistemaQuestoes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SistemaQuestoes().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel FUNDO;
    private javax.swing.JLabel INICIO;
    private java.awt.Choice choiceTipos;
    private javax.swing.JLabel icon;
    private javax.swing.JButton jButtonCadastrar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItemEditar;
    private javax.swing.JMenuItem jMenuItemExcluir;
    private javax.swing.JMenuItem jMenuItemListar;
    private javax.swing.JMenuItem jMenuItemVoltar;
    private javax.swing.JMenu jMenuQuestao;
    private javax.swing.JPanel jPanel1;
    private java.awt.TextArea textAreaQuestao;
    private java.awt.TextArea textAreaResposta;
    private javax.swing.JTextField txtAssunto;
    private javax.swing.JTextField txtID;
    // End of variables declaration//GEN-END:variables
}
