/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import javax.swing.JOptionPane;

/**
 *
 * @author pedro
 */
public class TelaInicial extends javax.swing.JFrame {

    /**
     * Creates new form TelaInicial
     */
    public TelaInicial() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jButtonCadastrar = new javax.swing.JButton();
        jButtonEntrar = new javax.swing.JButton();
        jButtonInstrucao = new javax.swing.JButton();
        jButtonCreditos = new javax.swing.JButton();
        jLabel_FUNDO = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Tela Início");
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setName("TelaInicio"); // NOI18N
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Times New Roman", 3, 18)); // NOI18N
        jLabel1.setText("Bem vindo(a) ao Simulados Softaware!");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 0, 300, 40));

        jButtonCadastrar.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jButtonCadastrar.setText("Cadastrar-se");
        jButtonCadastrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCadastrarActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonCadastrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 90, -1, -1));

        jButtonEntrar.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jButtonEntrar.setText("Entrar");
        jButtonEntrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonEntrarActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonEntrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 130, 90, -1));

        jButtonInstrucao.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jButtonInstrucao.setText("Instruções");
        jButtonInstrucao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonInstrucaoActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonInstrucao, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 180, 100, -1));

        jButtonCreditos.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jButtonCreditos.setText("Créditos");
        jButtonCreditos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCreditosActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonCreditos, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 220, 90, -1));

        jLabel_FUNDO.setForeground(new java.awt.Color(255, 255, 255));
        jLabel_FUNDO.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/provinha.png"))); // NOI18N
        getContentPane().add(jLabel_FUNDO, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 415, 313));

        getAccessibleContext().setAccessibleDescription("");

        setSize(new java.awt.Dimension(416, 339));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonCadastrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCadastrarActionPerformed
        TelaCadastro tela = new TelaCadastro();
        tela.setVisible(true);
        dispose();
    }//GEN-LAST:event_jButtonCadastrarActionPerformed

    private void jButtonEntrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonEntrarActionPerformed
        TelaEntrar tela = new TelaEntrar();
        tela.setVisible(true);
        dispose();
    }//GEN-LAST:event_jButtonEntrarActionPerformed

    private void jButtonInstrucaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonInstrucaoActionPerformed
        JOptionPane.showMessageDialog(rootPane, "Trabalhando ainda nisso!");
    }//GEN-LAST:event_jButtonInstrucaoActionPerformed

    private void jButtonCreditosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCreditosActionPerformed
        JOptionPane.showMessageDialog(rootPane, "Trabalhando ainda nisso!");
    }//GEN-LAST:event_jButtonCreditosActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaInicial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaInicial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaInicial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaInicial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaInicial().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonCadastrar;
    private javax.swing.JButton jButtonCreditos;
    private javax.swing.JButton jButtonEntrar;
    private javax.swing.JButton jButtonInstrucao;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel_FUNDO;
    // End of variables declaration//GEN-END:variables
}
